forci_lexik_translation_ui_list:
    path:     /translations
    defaults: { _controller: Forci\Bundle\LexikTranslationUIBundle\Controller\RestController::listAction }
    methods:  [GET]

forci_lexik_translation_ui_profiler:
    path:     /translations/profiler/{token}
    defaults: { _controller: Forci\Bundle\LexikTranslationUIBundle\Controller\RestController::listByProfileAction }
    methods:  [GET]

forci_lexik_translation_ui_update:
    path:     /translations/{id}
    defaults: { _controller: Forci\Bundle\LexikTranslationUIBundle\Controller\RestController::updateAction }
    methods:  [PUT]

forci_lexik_translation_ui_delete_locale:
    path:     /translations/{id}/{locale}
    defaults: { _controller: Forci\Bundle\LexikTranslationUIBundle\Controller\RestController::deleteTranslationAction }
    methods:  [DELETE]

forci_lexik_translation_ui_delete:
    path:     /translations/{id}
    defaults: { _controller: Forci\Bundle\LexikTranslationUIBundle\Controller\RestController::deleteAction }
    methods:  [DELETE]
