export const TRANSLATION_LIST = 'TRANSLATION_LIST';
export const TRANSLATION_CREATE = 'TRANSLATION_CREATE';
export const TRANSLATION_UPDATE = 'TRANSLATION_UPDATE';
export const TRANSLATION_DELETE = 'TRANSLATION_DELETE';
export const TRANSLATION_SYNC = 'TRANSLATION_SYNC';
export const STATISTICS_LOAD = 'STATISTICS_LOAD';